##############################################################
# The following optons affect the Markdown export
##############################################################

## Destination
basepath: 'export'
## Select meta data options
meta_data_in_yaml: False  # True a YAML front matter block will contain the following meta data items.  
                           # False any selected meta data options below will be in the md text
insert_title: True  # True will add the title of the note as a field in the YAML block, False no title in block.
insert_ctime: False  # True to insert note creation time in the YAML block, False to disable.
insert_mtime: False  # True to insert note modification time in the YAML block, False to disable.
tags: True  # True to insert list of tags, False to disable
tag_prepend: ''  # string to prepend each tag in a tag list inside the note, default is empty
tag_delimiter: ', '  # string to delimit tags, default is comma separated list
no_spaces_in_tags: False  # True to replace spaces in tag names with '_', False to keep spaces

## Select file link options
links_as_URI: True  # True for file://link%20target style links, False for /link target style links
absolute_links: True  # True for absolute links, False for relative links

## Select File/Attachments/Media options
creation_date_in_filename: False  # True to insert note creation time to the note file name, False to disable.

##############################################################
# The following optons affect the Paperless-ngx export
##############################################################

# destination
paperless_url: "http://localhost:8000"

# credentials
username: "user"
password: "password"
# using the basic auth, the code will retrieve the user token and use it for all transactions.
# optionally, simply provide the Paperless user token directly.
#token: 'azertyuiopqsdfghjklmwxcvbn'

# timeout for API requests
timeout: 5.0
# extensions to be exported
extensions: [".pdf", ".jpg", ".png", ".jpeg", ".gif", ".tif", ".tiff", ".webp", ".txt", ".docx", ".doc", ".odt", ".ppt", ".pptx", ".odp", ".xls", ".xlsx", ".ods"]
# extensions to be ignored when the note contains an html attachment
htmlnote_ignore: [".jpg", ".png", ".jpeg", ".gif", ".webp", ".tif", ".tiff"]
# timezone used to convert NoteStation timestamps to ISO strings
timezone: 'Europe/Brussels'

